title: MinBRectï¼šAn Efficient Visual Grasping Algorithm and System for Robotic Arm Based on RGB-D Image
description: Grab experimental videos display
show_downloads: false
theme: jekyll-theme-cayman
github:
  is_project_page: false
